#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy

printf %s "
frontend hbnb-lb_front
        bind *:80
        mode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        balance roundrobin
        server 284781-web-01 54.172.84.11:80 check
        server 284781-web-02 18.210.17.119:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
