#!/usr/bin/python3
"""
Recursive function that queries the Reddit API and returns a list
containing the titles of all hot articles for a given subreddit.
"""
import requests

def recurse(subreddit, hot_list=[]):
    """Returns None if subreddit is not found."""
    api_url = f"https://www.reddit.com/r/{subreddit}/hot.json"
    headers = {"User-Agent": "MyScript"}

    response = requests.get(api_url, headers=headers)

    if response.status_code == 200:
        data = response.json()
        posts = data["data"]["children"]

        for post in posts:
            title = post["data"]["title"]
            hot_list.append(title)

        if data["data"]["after"] is not None:
            # make recursive call with the "after" parameter to get the next page of results
            return recurse(subreddit, hot_list=hot_list, after=data["data"]["after"])
        else:
            return hot_list
